---
- hosts : all
  remote_user: root
  tasks:
    - name: Install Nginx Web Server
      yum: name=nginx state=latest
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted